exclude: [README.md, Vagrantfile, provision, .gitignore, .vagrant]

collections:
  posts:
    output: true

defaults:
  -
    scope:
      path: "articles"
      type: "posts"
    values:
      layout: "post"

