exclude: [README.md, Vagrantfile, .gitignore, .vagrant]

permalink: /blog/:title/

collections:
  pages:
    output: true
    permalink: /:title/
    layout: "default"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
